### ISSUE TITLE
Issues with running solidity-coverage

### ISSUE THREAD

**Issue by hemantasapkota** [xceltripofficial/xceltoken#4]
I'm creating this issue so we can revisit this later. 

solidity-coverage complains that it can't find MintableToken, which doesn't make sense since the file is clearly there!!

```
Generating coverage environment
Running: truffle compile
(this can take a few seconds)...
Error: Could not find zeppelin-solidity/contracts/token/ERC20/MintableToken.sol from any sources; imported from /Users/lexsapkota/go/src/xcltoken/coverageEnv/contracts/MintableTestPlaceholder.sol
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:76:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/whilst.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:64:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:85:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/once.js:12:1
    at replenish (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:59:1)
    at iterateeCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:49:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:81:1)
ls: no such file or directory: ./coverageEnv/build/contracts/*.json
Skipping instrumentation of  ./coverageEnv/contracts/Migrations.sol
Instrumenting  ./coverageEnv/contracts/MintableTestPlaceholder.sol
Instrumenting  ./coverageEnv/contracts/StepVesting.sol
Instrumenting  ./coverageEnv/contracts/XcelToken.sol
Running: truffle compile
(this can take a few seconds)...
Error: Could not find zeppelin-solidity/contracts/token/ERC20/MintableToken.sol from any sources; imported from /Users/lexsapkota/go/src/xcltoken/coverageEnv/contracts/MintableTestPlaceholder.sol
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:76:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/whilst.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:64:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:85:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/once.js:12:1
    at replenish (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:59:1)
    at iterateeCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:49:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:81:1)
ls: no such file or directory: ./coverageEnv/build/contracts/*.json
Launched testrpc on port 8555
Running: truffle test
(this can take a few seconds)...
Error: Could not find zeppelin-solidity/contracts/token/ERC20/MintableToken.sol from any sources; imported from /Users/lexsapkota/go/src/xcltoken/coverageEnv/contracts/MintableTestPlaceholder.sol
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:76:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at next (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/whilst.js:68:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/index.js:64:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:85:1
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/once.js:12:1
    at replenish (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:59:1)
    at iterateeCallback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/eachOfLimit.js:49:1)
    at /usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/~/async/internal/onlyOnce.js:12:1
    at ReadFileContext.callback (/usr/local/lib/node_modules/truffle/build/webpack:/~/truffle-resolver/fs.js:81:1)
    at FSReqWrap.readFileAfterOpen [as oncomplete] (fs.js:437:13)
Cleaning up...
Event trace could not be read.
Error: ENOENT: no such file or directory, open './allFiredEvents'
Exiting without generating coverage...
```

**Comment by maxxbw54** [comment]
Hi, @hemantasapkota , have you solved the problem？ I meet the same issue as yours.
